### ISSUE TITLE
Battery report not working

### ISSUE THREAD

**Issue by Swimming33** [jamesfawcett/Thinkpad-X2100-51nb-OpenCore-Hackintosh#2]
Currently cannot get the battery status report to work with my X2100. Unsure if this is an issue with my configuration of OpenCore, or if there's some sort of BIOS setting I need to change (there's about a bajillion of them, and I've tried a few). 

Obviously open to trying anything, this sort of problem is to be expected when you're playing with Hackintosh on laptop.

**Comment by jamesfawcett** [comment]
Hi @Swimming33 this is strange, not an issue I've come across, I swap my batteries quite often I have 6 cell and a 9 cell, all work quite well and report charge and health correctly. Does the battery reporting work correctly in other OS's? I've also tried non-genuine batteries and they work for me too.

**Comment by Swimming33** [comment]
Battery reporting *does* work on Windows and Linux, so I got no clue lol. I'm gonna try reinstalling everything, just on the basis that something's borked (It's worked on prior installs). 

Will keep you updated, not that it really matters too much, haha!

**Comment by jamesfawcett** [comment]
Hi @Swimming33 would you mind trying again?

I've experienced the same after upgrading to latest Monterey, I've now swapped to using USBMap for ports and not Hackintool from here: https://github.com/corpnewt/USBMap 

Everything working for me now on latest OS including sleep. It's a cool feature being able to plug SD Card into the front slot and it appear on Mac desktop!

**Comment by Swimming33** [comment]
Sorry for the *very late reply*. I did try that, and it all works now! Do have some other minor issues (again... to be expected with a Hackintosh setup like this lol), but I'll open another ticket and close this one! Thanks for all the help, really!
