### ISSUE TITLE
External monitors don't work via USB-C

### ISSUE THREAD

**Issue by jafd** [jamesfawcett/Thinkpad-X2100-51nb-OpenCore-Hackintosh#6]
With the SMBIOS provided, which is for MacBookPro16,1, external monitors plugged in via USB-C will not work. The reason is that macOS looks at the model number to see which output routes where, and this particular model has a discrete GPU through which all external monitors are supposed to work.

If you use MacBookPro15,4, which is of the same year (and the same processor), but uses internal graphics card for everything, monitors will work.

**Comment by jamesfawcett** [comment]
Thank you for this - I've updated the notes and default. I don't use external monitors I find the 3000x2000 display is enough but I did quite often on my X330. 

I've altered my Bios settings this week too from [here](https://github.com/xy-tech/X2100-BIOS-EC#instructions-to-update), and its running silent now, very quiet.
